# Project: ch01
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = sum.o main.o $(RES)
LINKOBJ  = sum.o main.o $(RES)
LIBS =  -L"D:/mee/Apps/PortableApps/Dev-CppPortable/App/devcpp/lib"  -g3 
INCS =  -I"D:/mee/Apps/PortableApps/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"D:/mee/Apps/PortableApps/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/mee/Apps/PortableApps/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"D:/mee/Apps/PortableApps/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"D:/mee/Apps/PortableApps/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"D:/mee/Apps/PortableApps/Dev-CppPortable/App/devcpp/include" 
BIN  = ch01.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ch01.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "ch01.exe" $(LIBS)

sum.o: sum.c
	$(CC) -c sum.c -o sum.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
